name = "moviimovel-grok-worker"
main = "worker.js"
compatibility_date = "2026-06-24"
keep_vars = true

[ai]
binding = "AI"

[vars]
CLOUDFLARE_ACCOUNT_ID = "4bb140923d5cbe7d8c4bb04c514f44d6"
GROK_480P_PER_SECOND = "0.08"
GROK_720P_PER_SECOND = "0.14"
